"""NEXTRACE AI — Plain-language explanation API"""
from __future__ import annotations

import asyncio
import ipaddress
from typing import Annotated, List, Literal, Optional

from fastapi import APIRouter
from pydantic import BaseModel, Field, StringConstraints, field_validator

from backend.services.explainer import explain

router = APIRouter()

Category = Literal[
    "icmp_recon", "port_scan", "auth_probe", "lateral_movement", "suspicious_dns",
    "data_transfer", "c2_channel", "traffic_flood", "anomalous_flow",
]
Severity = Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]
Stage = Literal[
    "Reconnaissance", "Initial Access", "Lateral Movement", "Command & Control",
    "Data Exfiltration", "Impact", "Observed Activity",
]
# Labels are generated by the grouping engine; the pattern keeps free text (and prompt injection) out.
Label = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=80, pattern=r"^[A-Za-z0-9 /&()+.,:'-]+$")]
ActivityId = Annotated[str, StringConstraints(pattern=r"^[A-Z]{2,5}-\d{1,6}$")]
MitreId = Annotated[str, StringConstraints(pattern=r"^T\d{4}(\.\d{3})?$")]


def _host(v: str) -> str:
    """An IP address or network (detectors may report a sweep target as a /24); anything else is rejected."""
    if v == "multiple_targets":
        return v
    try:
        return str(ipaddress.ip_address(v))
    except ValueError:
        return str(ipaddress.ip_network(v, strict=False))  # raises ValueError for non-network input


class ActivityFacts(BaseModel):
    id: ActivityId
    category: Category
    label: Label
    severity: Severity
    stage: Stage
    sources: List[str] = Field(..., max_length=10)
    targets: List[str] = Field(..., max_length=10)
    ports: List[int] = Field(default_factory=list, max_length=50)
    event_count: int = Field(..., ge=0, le=100_000_000)
    duration_seconds: int = Field(..., ge=0, le=31_536_000)
    bytes: Optional[int] = Field(None, ge=0)
    mitre_id: Optional[MitreId] = None

    @field_validator("sources", "targets")
    @classmethod
    def _hosts(cls, v: List[str]) -> List[str]:
        return [_host(x) for x in v]

    @field_validator("ports")
    @classmethod
    def _ports(cls, v: List[int]) -> List[int]:
        if any(p < 0 or p > 65535 for p in v):
            raise ValueError("ports must be 0-65535")
        return v


class Totals(BaseModel):
    packets: int = Field(..., ge=0, le=1_000_000_000)
    flows: int = Field(..., ge=0, le=1_000_000_000)
    duration_seconds: int = Field(..., ge=0, le=31_536_000)


class ExplainRequest(BaseModel):
    context: Literal["historical", "live", "investigation"]
    totals: Totals
    activities: List[ActivityFacts] = Field(..., max_length=30)


@router.post("/explain")
async def explain_endpoint(body: ExplainRequest) -> dict:
    """Plain-language explanation of grouped activities (LLM when configured, template otherwise)."""
    facts = body.model_dump()
    # The LLM call is blocking I/O with its own timeout; keep it off the event loop.
    return await asyncio.to_thread(explain, facts)
